### ISSUE TITLE
Error loading with start

### ISSUE THREAD

**Issue by ghost** [Deftu/BetterGamma#2]
Hello, I get an error when starting minecraft with your mod.  Here are the logging files
[log.txt](https://github.com/user-attachments/files/15859947/log.txt)

**Comment by Deftu** [comment]
You need to install [DeftuLib](https://modrinth.com/mod/deftulib) to use BetterGamma.

**Comment by ghost** [comment]
Thanks, it works. Could you also indicate this in the description of your mod on modrinth.com so that users don't encounter this problem anymore?

**Comment by Deftu** [comment]
I'll add it when I revamp the pages.
